kind: pipeline
name: default

steps:
  - name: build
    image: node:10
    commands:
      - npm install
      - npm run build

  - name: publish
    image: plugins/gh-pages
    settings:
      username:
        from_secret: deploy_user
      password:
        from_secret: deploy_key
      pages_directory: build/
